#index:
#    path: /
#    controller: App\Controller\DefaultController::index

hook:
    path: /hook
    controller: App\Controller\HookController::hook

set:
    path: /set/{authToken}
    controller: App\Controller\HookController::set